
name: Math Boster App

on: 
  pull_request: 
  branches:
    - main

jobs:
  tests:
  runs-on: windows-latest
  container:
    image: node:20
  steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20
    - run: npm ci
    - run: npm test
    - run: npm run build




